sync .github and cobalt/tools directories from main

diff --git a/.github/actions/on_device_tests/action.yaml b/.github/actions/on_device_tests/action.yaml
--- a/.github/actions/on_device_tests/action.yaml
+++ b/.github/actions/on_device_tests/action.yaml
@@ -1,6 +1,9 @@
 name: On Device Test
 description: Runs on-device tests.
 inputs:
+  nightly:
+    description: "Indicates if this is a nightly job."
+    required: true
   test_targets_json:
     description: "The test targets in a JSON array."
     required: true
@@ -71,7 +74,7 @@ runs:
           --test_type ${TEST_TYPE} \
           --device_family '${{ inputs.test_device_family }}' \
           --targets '${{ inputs.test_targets_json }}' \
-          --filter_json_dir "${GITHUB_WORKSPACE}/cobalt/testing/filters/${{ matrix.platform}}" \
+          --filter_json_dir "${GITHUB_WORKSPACE}/cobalt/testing/filters/${{ matrix.platform }}" \
           --label chrobalt_on_device_test \
           --label github_${GITHUB_PR_NUMBER:-postsubmit} \
           --label builder-${{ matrix.platform }} \
@@ -101,15 +104,44 @@ runs:
       shell: bash
     - name: Download ${{ matrix.platform }} Test Results from GCS
       if: always()
+      env:
+        TEST_TARGETS_JSON: ${{ inputs.test_targets_json }}
       run: |
         set -uxe
+        shopt -s globstar nullglob
+
         test_output="${GITHUB_WORKSPACE}/results"
         echo "test_output=${test_output}" >> $GITHUB_ENV
 
-        # Test results (xml and logs) must be in a subfolder in results_dir
+        # Test results (xml and logs) must be in a subfolder in results_dir.
         # to be picked up by the test result processor.
         mkdir -p "${test_output}/${{ matrix.platform }}"
         gsutil -q cp -r "${{ inputs.gcs_results_path }}/" "${test_output}/${{ matrix.platform }}"
+
+        # Check for missing result xml files.
+        readarray -t test_targets < <(echo "$TEST_TARGETS_JSON" | jq -r '.[]')
+        for test_target_with_path in "${test_targets[@]}"; do
+          # Trim path prefix (before :).
+          test_target=${test_target_with_path#*:}
+          xml_files=("${test_output}"/${{ matrix.platform }}/**/"${test_target}"_testoutput.xml)
+          if [[ "${#xml_files[@]}" -eq 0 ]]; then
+            # No matching XML results found. Check if the test target is filtered.
+            test_filter_file="${GITHUB_WORKSPACE}/cobalt/testing/filters/${{ matrix.platform }}/${test_target}_filter.json"
+            if [ ! -f "${test_filter_file}" ] || [ "$(jq -cr '.failing_tests[0]' "${test_filter_file}")" != '*' ]; then
+              echo "Test result xml is missing for ${test_target}."
+
+              # Try to find the crashed test in the log and create a fake junit xml for it.
+              log_path=("${test_output}"/${{ matrix.platform }}/**/"${test_target}"_log.txt)
+              xml_path=("${test_output}"/${{ matrix.platform }}/1/"${test_target}"_testoutput.xml)
+              python3 ${GITHUB_WORKSPACE}/.github/scripts/generate_crash_report.py "${log_path}" "${xml_path}"
+              exit 1
+            fi
+          elif grep -e '<failure' -e '<error' ${xml_files}; then
+            # Double-check the result XML for failures. ODT service has been known to report incorrect status.
+            echo "::error::Found failures in the test xml."
+            exit 1
+          fi
+        done
       shell: bash
     - name: Archive Test Results
       uses: actions/upload-artifact@v4
@@ -117,3 +149,15 @@ runs:
       with:
         name: ${{ inputs.test_results_key }}
         path: ${{ env.test_output }}/*
+    - name: Get Deflake Max Attempts
+      id: deflake-attempts
+      if: inputs.nightly == 'true'
+      run: |
+        MAX_ATTEMPTS=$(jq -r '.deflake_runs | tonumber? // 1' ${GITHUB_WORKSPACE}/.github/config/infra/deflake.json)
+        echo "max_attempts=${MAX_ATTEMPTS}" >> $GITHUB_OUTPUT
+      shell: bash
+    - name: Run Nightly Deflake
+      # Deflake workflow retries MAX_ATTEMPTS times. Pass the last to keep dashboard green.
+      if: inputs.nightly == 'true' && github.run_attempt != steps.deflake-attempts.outputs.max_attempts
+      run: echo "::warning::Triggering deflaking run by failing." && exit 1
+      shell: bash
diff --git a/.github/actions/on_host_tests/action.yaml b/.github/actions/on_host_tests/action.yaml
--- a/.github/actions/on_host_tests/action.yaml
+++ b/.github/actions/on_host_tests/action.yaml
@@ -1,6 +1,9 @@
 name: On Host Tests
 description: Runs on-host tests.
 inputs:
+  nightly:
+    description: "Indicates if this is a nightly job."
+    required: true
   test_artifacts_key:
     description: "Artifact key used to store test artifacts."
     required: true
@@ -14,20 +17,16 @@ runs:
   using: "composite"
   steps:
     - name: Download Artifacts
-      uses: actions/download-artifact@v4
+      uses: actions/download-artifact@v5
       with:
         name: ${{ inputs.test_artifacts_key }}
     - name: Extract Artifacts
       shell: bash
       run: |
         set -x
-
-        test_dir="${GITHUB_WORKSPACE}/unit_test"
-        echo "test_dir=${test_dir}" >> $GITHUB_ENV
-
-        mkdir -p ${test_dir}
-        cd ${test_dir}
-        tar xvf ../test_artifacts.tar.gz
+        mkdir -p unit_test/
+        cd unit_test/
+        tar -I 'zstd -T0' -xf ../test_artifacts.tar.zstd
     - name: Run Tests
       id: run-tests
       shell: bash
@@ -37,10 +36,15 @@ runs:
         set -x
         env
 
-        # Explicitly point to libraries in extracted dir.
-        LD_LIBRARY_PATH="${test_dir}/out/${{ matrix.platform}}_${{ matrix.config }}/starboard"
-        LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${test_dir}/out/${{ matrix.platform}}_${{ matrix.config }}"
+        out_dir="${GITHUB_WORKSPACE}/unit_test/out/${{ matrix.platform}}_${{ matrix.config }}"
+        # TODO: LD_LIBRARY_PATH should not include the starboard subdirectory.
+        LD_LIBRARY_PATH="${out_dir}/starboard"
+        LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${out_dir}"
         export LD_LIBRARY_PATH
+
+        # TODO: b/467135717 - Remove this once tests don't have asan leaks.
+        # Don't fail if only asan fails.
+        export ASAN_OPTIONS=exitcode=0
 
         # Make results dir available to the archiving step below.
         results_dir="${GITHUB_WORKSPACE}/results"
@@ -53,13 +57,17 @@ runs:
         mkdir -p ${test_output}
 
         failed_suites=""
-        cd "${test_dir}"
+        cd unit_test/
 
-        for test_binary_path in $(cat out/${{ matrix.platform}}_${{ matrix.config }}/test_targets.json | jq -cr '.executables | join(" ")'); do
-          test_binary=$(basename "${test_binary_path}")
-          if [[ "${{ matrix.platform}}" == *"evergreen"* ]]; then
-            test_binary_path=${test_binary_path}_loader
+        for test_binary_path in $(cat out/${{ matrix.platform }}_${{ matrix.config }}/test_targets.json | jq -cr '.executables | join(" ")'); do
+          filename=$(basename "${test_binary_path}")
+          test_binary="${filename%%.*}"
+
+          if [[ "${{ matrix.shard }}" != "0" && "${test_binary}" =~ ^nplb ]]; then
+            # Workaround for nplb not supporting sharding.
+            continue
           fi
+
           echo "Running tests for suite: ${test_binary}"
 
           test_filter="*"
@@ -73,21 +81,29 @@ runs:
           log_path="${test_output}/${test_binary}_log.txt"
           # TODO: Investigate test_runner.py
 
+          ENTRYPOINT=./"${test_binary_path}"
+
           if [ "${test_filter}" == "-*" ]; then
             echo "Skipped due to test filter." >  ${log_path}
           else
             export GTEST_TOTAL_SHARDS=${{ inputs.num_gtest_shards }}
             export GTEST_SHARD_INDEX=${{ matrix.shard }}
             /usr/bin/xvfb-run -a --server-args="${XVFB_SERVER_ARGS}" \
-                stdbuf -i0 -o0 -e0 ./"${test_binary_path}" \
+                stdbuf -i0 -o0 -e0 $ENTRYPOINT \
+                --single-process-tests \
                 --gtest_output="xml:${xml_path}" \
                 --gtest_filter="${test_filter}" 2>&1 | tee ${log_path} || {
               failed_suites="${failed_suites} ${test_binary}"
             }
+
+            if [[ ! -f ${xml_path} ]]; then
+              # Test binary crashed. Generate a fake JUnit XML report with the last run test.
+              python3 ${GITHUB_WORKSPACE}/.github/scripts/generate_crash_report.py "${log_path}" "${xml_path}"
+            fi
           fi
         done
         echo "Finished running tests..."
-        if [ -n "${failed_suites}" ]; then
+        if [[ -n "${failed_suites}" ]]; then
           echo "Test suites failed:${failed_suites}"
           # Fail the job so it's easy to retrigger.
           exit 1
@@ -98,3 +114,15 @@ runs:
       with:
         name: ${{ inputs.test_results_key }}
         path: ${{ env.results_dir }}/*
+    - name: Get Deflake Max Attempts
+      if: inputs.nightly == 'true'
+      id: deflake-attempts
+      run: |
+        MAX_ATTEMPTS=$(jq -r '.deflake_runs | tonumber? // 1' ${GITHUB_WORKSPACE}/.github/config/infra/deflake.json)
+        echo "max_attempts=${MAX_ATTEMPTS}" >> $GITHUB_OUTPUT
+      shell: bash
+    - name: Run Nightly Deflake
+      # Deflake workflow retries MAX_ATTEMPTS times. Pass the last to keep dashboard green.
+      if: inputs.nightly == 'true' && github.run_attempt != steps.deflake-attempts.outputs.max_attempts
+      run: echo "::warning::Triggering deflaking run by failing." && exit 1
+      shell: bash
diff --git a/.github/actions/process_test_results/action.yaml b/.github/actions/process_test_results/action.yaml
--- a/.github/actions/process_test_results/action.yaml
+++ b/.github/actions/process_test_results/action.yaml
@@ -7,8 +7,11 @@ inputs:
   datadog_api_key:
     description: "Path to directory where test results are saved."
     default: ''
-  results_path:
+  results_glob:
     description: "Path (or glob) to test result xml files."
+    required: true
+  num_gtest_shards:
+    description: Number of gtest shards run.
     required: true
 runs:
   using: "composite"
@@ -17,37 +20,61 @@ runs:
       id: test-summary
       uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86
       with:
-        paths: ${{ inputs.results_path }}
+        paths: ${{ inputs.results_glob }}
         output: test-report-summary.md
         show: "fail, skip"
 
     - name: Populate GitHub Summary
+      if: steps.test_summary.outputs.failed > 0
       run: cat test-report-summary.md >> $GITHUB_STEP_SUMMARY
       shell: bash
 
     - name: Check Failed Tests
       if: always()
       run: |
-        set -x
+        # Check test status.
+        exit_code=0
+
         # Enable globstar shell option for globstar paths e.g. /**/*.xml and
         # nullglob to return empty string if the glob matches no files.
         shopt -s globstar nullglob
 
-        result_xmls=(${{ inputs.results_path }})
-        if [ ${#result_xmls[@]} -eq 0 ]; then
-          echo "::error::No test results found. Did the test crash?"
-          exit 1
+        # Workaround for nplb not supporting sharding.
+        num_shards=${{ inputs.num_gtest_shards }}
+        if [[ "${{ inputs.results_glob }}" =~ nplb ]]; then
+          num_shards=1
         fi
+
+        result_xmls=(${{ inputs.results_glob }})
+        if [ ${#result_xmls[@]} -ne ${num_shards} ]; then
+          echo "::error::Missing test result xml (found ${#result_xmls[@]}, expected ${{ inputs.num_gtest_shards }}). Did a test shard crash?"
+          exit_code=1
+        fi
+
         if [ ${{ steps.test-summary.outputs.failed }} -gt 0 ]; then
+          # Print failed tests.
+          echo
+          echo " _____ _____ ____ _____   ____ _____   _   _____ _   _  ____  "
+          echo "|_   _| ____/ ___|_   _| / ___|_   _| / \ |_   _| | | |/ ___| "
+          echo "  | | |  _| \___ \ | |   \___ \ | |  / _ \  | | | | | |\___ \ "
+          echo "  | | | |___ ___) || |    ___) || | / ___ \ | | | |_| | ___) |"
+          echo "  |_| |_____|____/ |_|   |____/ |_|/_/   \_\|_|  \___/ |____/ "
+          echo
+
+          python3 cobalt/tools/junit_mini_parser.py ${{ inputs.results_glob }}
+
           echo "::error::${{ inputs.target_name }} has ${{ steps.test-summary.outputs.failed }} failed test(s)."
-          exit 1
+          exit_code=1
         fi
+
+        exit ${exit_code}
       shell: bash
 
     - name: Get Datadog CLI
       id: download-dd-cli
       # The API key is not available on PRs created from a fork.
       if: always() && inputs.datadog_api_key != ''
+      continue-on-error: true
       env:
         DD_VERSION: 'v2.18.0'
         DD_SHA256SUM: 'adbe9b3a41faaf0b1d9702ba256cf8fa9e474c0cc8216f25e5b489c53d6f0a70  datadog-ci'
@@ -59,8 +86,9 @@ runs:
         chmod +x datadog-ci
       shell: bash
 
-    - name: Upload to Datadog
+    - name: Upload Results to Datadog
       if: always() && steps.download-dd-cli.outcome == 'success'
+      continue-on-error: true
       env:
         DATADOG_SITE: us5.datadoghq.com
         DATADOG_API_KEY: ${{ inputs.datadog_api_key }}
@@ -71,5 +99,5 @@ runs:
         set -x
         # Enable globstar shell option for globstar paths e.g. /**/*.xml
         shopt -s globstar
-        ./datadog-ci junit upload --service ${DD_SERVICE} ${{ inputs.results_path }}
+        ./datadog-ci junit upload --service ${DD_SERVICE} ${{ inputs.results_glob }}
       shell: bash
